force revert to 10f770

diff --git a/scripts/race b/scripts/race
--- a/scripts/race
+++ b/scripts/race
@@ -168,13 +168,7 @@ fi
 #
 # prepare __race temp folder in simdist
 #
-if [ "$mode" == "final" ]; then
-    if [ ! -f "$ETROBO_ROOT/CONTINUE" ]; then
-        rm -rf "$raceTemp"
-    fi
-else
-    rm -rf "$raceTemp"
-fi
+rm -rf "$raceTemp"
 mkdir -p "$raceTemp"
 cd "$ETROBO_SIM_DIST"
 rm -f *.zip
@@ -299,24 +293,16 @@ else
             rm -f "$raceFolder/WAITING"
         fi
         cp "$raceFolder/Requests/$target" "$ETROBO_SIM_DIST"
-        unset continue
-        if [ "$mode" == "final" ] && [ -f "$ETRBO_ROOT/CONTINUE" ]; then
-            continue="continue"
+        unzip -o $target > /dev/null
+        unzip_error="$?"
+        if [ "$mode" != "get" ]; then
+            rm -f "$raceFolder/Requests/$target"
         fi
-        if [ -z "$continue" ]; then
-            unzip -o $target > /dev/null
-            unzip_error="$?"
-            if [ "$mode" != "get" ]; then
-                rm -f "$raceFolder/Requests/$target"
-            fi
-            if [ "$unzip_error" != "0" ]; then
-                echo "race sequencer: UNZIP ERROR"
-                exit $ERR_SEQ_UNZIP_FAILED
-            fi
-            rm "$ETROBO_SIM_DIST/$target"
-        else
-            rm -f "$ETRBO_ROOT/CONTINUE"
+        if [ "$unzip_error" != "0" ]; then
+            echo "race sequencer: UNZIP ERROR"
+            exit $ERR_SEQ_UNZIP_FAILED
         fi
+        rm "$ETROBO_SIM_DIST/$target"
         if [ ! -d __race ]; then
             echo "race sequencer: $target isn't contain '__race' folder."
             exit $ERR_SEQ_RACE_NOT_FOUND
